nome=input('Digite seu nome Completo: ')
mai=nome.upper()
min=nome.lower()
total=nome.replace(' ', '')
total2= len(total)
primeiro=nome.split()
print("Seu nome completo é: {}".format(nome))
print("Em maiuscula: {}".format(mai))
print('Em minuscula: {}'.format(min))
print("total de letras: {}".format(total2))
print('E seu primenro nome tem {}'.format(len(primeiro[0])))
